### ISSUE TITLE
withScope not working?

### ISSUE THREAD

**Issue by chrisdrackett** [BrunoScheufler/graphql-middleware-sentry#107]
I'm successfully seeing errors sent to sentry, but anything within my withScope does not seem to be making it. Even the following:

```
export const sentryMiddleware = sentry({
  config: {
    dsn: 'secret',
    environment: process.env.NODE_ENV,
  },
  withScope: (scope, error, context) => {
    scope.setUser({
      id: 'testID',
    })
  },
})
```

is not sending the ID with the error to sentry (I'm just getting an IP)

**Comment by BrunoScheufler** [comment]
That's really strange, I don't think we're doing anything special with the scope in that case, the only part we're handling it would be the following

```typescript
sentryInstance.withScope(scope => {
    withScope(scope, error, ctx)
    sentryInstance.captureException(error)
})
```

Did you already try using a custom Sentry instance passed in instead of just the DSN which will create an internal Sentry instance? Maybe this could work, otherwise I'm not sure if this is caused by some potential bug in this middleware or rather Sentry itself 🤔
