### ISSUE TITLE
Filter Errors by Type

### ISSUE THREAD

**Issue by mfruhner** [BrunoScheufler/graphql-middleware-sentry#40]
Hey, i got another question.
Is it possible, to filter incoming errors?
I would like to not send 'UnauthorizedError's and such to sentry, but still notify the client about it.
I could not find any helpful info about it.

Thanks!

**Comment by herkulano** [comment]
The `captureReturnedErrors` option might help in the case of errors coming from `graphql-shield`.

**Comment by mattfwood** [comment]
I'm also having this issue, where I'm throwing some custom errors (for example, "You must be logged in to do that") that I want the user to see, but I don't want to report to Sentry.

I think that in the config, maybe we could add something like "ignoreInstancesOf" and give that a custom error type, and then instead of doing:

```javascript
throw new Error('You must be logged in')
```

You could use something like:
```javascript
throw new CustomError('You must be logged in')
```

And ignore it, even if you're not using graphql-shield.

**Comment by mattfwood** [comment]
I just created #50, I think this would implement the request feature fairly well.

**Comment by BrunoScheufler** [comment]
Hey there to all of you! I've just taken over this package to free some time of @maticzav who asked me 👍 I will look after the PRs shortly after I get everything up and running here 😄
